# End Points para categoria Para categoria
# Endpoints para a categoria
###
POST http://localhost:5000/auth HTTP/1.1
Content-Type: application/json

{
  "username": "usuarioteste",
  "password": "senhateste"
}
###

GET http://localhost:5000/categoria
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW90ZXN0ZSIsImlhdCI6MTY4ODM0MTIzOX0.0q-L9DWWx5-xvJrFI7Vb7aCJgkBufvGg0Ebtr-znloU


###
GET http://localhost:5000/categoria/1 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:5000/categoria/1 HTTP/1.1
Content-Type: application/json

{
    "id_categoria": 1,
    "nome_categoria": "Vestuário"
}

###
DELETE http://localhost:5000/categoria/9 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/categoria HTTP/1.1
Content-Type: application/json

{
    "id_categoria": 12,
    "nome_categoria": "Blusa de frio"
}

###
POST http://localhost:5000/produto HTTP/1.1
Content-Type: application/json


{
    "cod_produto": 13,
    "nome_produto": "Blusa de frio",
    "qtde_produto": 2,
    "id_categoria": 1 
}
###

GET http://localhost:5000/produto HTTP/1.1
Content-Type: application/json
###

GET http://localhost:5000/produto/5 HTTP/1.1
Content-Type: application/json
###

PUT http://localhost:5000/produto/5  HTTP/1.1
Content-Type: application/json

{
    "cod_produto": 10,
    "nome_produto": "Blusa de frio",
    "qtde_produto": 2,
    "id_categoria": 1 
}

###
DELETE http://localhost:5000/produto/5 HTTP/1.1
Content-Type: application/json

###

###
GET http://localhost:5000/pedido/1 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:5000/pedido/1 HTTP/1.1
Content-Type: application/json

{
    "num_pedido": 1,
    "cod_produto": 2,
    "qtde_pedido": 4
}
